# Generated by Django 4.1.7 on 2023-05-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='start_date',
            field=models.DateField(),
        ),
    ]
