# Generated by Django 4.1.7 on 2023-05-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetme', '0003_alter_meeting_end_date_alter_meeting_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='kst_number',
            field=models.IntegerField(),
        ),
    ]
