# Generated by Django 4.1.7 on 2023-05-03 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetme', '0004_alter_meeting_kst_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
