# Generated by Django 4.1.7 on 2023-05-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetme', '0006_alter_meeting_random_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='random_code',
            field=models.CharField(blank=True, default=3, max_length=30, null=True),
        ),
    ]
