# Generated by Django 4.1.7 on 2023-05-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetme', '0009_newusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newusers',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
