# Generated by Django 4.1.7 on 2023-05-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetme', '0011_delete_newusers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='random_code',
        ),
        migrations.AddField(
            model_name='meeting',
            name='number_of_quests',
            field=models.IntegerField(default=False),
        ),
    ]
