# Generated by Django 4.1.7 on 2023-09-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetme', '0014_meetinghistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='end_date',
            field=models.DateField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='start_date',
            field=models.DateField(blank=True, default=False, null=True),
        ),
    ]
