# Generated by Django 4.1.7 on 2024-06-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetme', '0015_alter_meeting_end_date_alter_meeting_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='recorded',
            field=models.BooleanField(default=False),
        ),
    ]
